config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'application#home'
  resources :users
  get '/signup', to: 'users#new'
  resources :comments
  get '/locations/:id/seasons'
  resources :locations do
    resources :crags
  end
  resources :locations
  # resources :crags, only: [:new, :create, :show, :edit, :update] do
  #   resources :comments
  #   end
  resources :sessions
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  root 'locations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :crag

end



# show user's comments with flag above each comment

app/models/crag.rb
class Crag < ApplicationRecord
  belongs_to :location
  has_many :comments
  has_many :users, through: :comments
  scope :winter, -> { where(season: ["winter", "Winter"])}
  scope :spring, -> { where(season: "spring").or.where(season: "Spring")}
  scope :summer, -> { where(season: "summer").or.where(season: "Summer")}
  scope :fall, -> { where(season: ["fall", "Fall"])}




end

# @spring_crags = @location.crags.spring

app/models/location.rb
class Location < ApplicationRecord
  has_many :crags
  accepts_nested_attributes_for :crags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :crags, through: :comments
  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :require_login, :except => [:home]

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= user = User.find(session[:user_id]) if session[:user_id]
  end

  def home
    render 'home/homepage'
  end

  def require_login
    unless current_user
      redirect_to '/'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @user = current_user
    @comment.user = @user
    if @comment.save
      redirect_to location_crag_path(@comment.crag.location, @comment.crag)
    else
      redirect_to locations_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:crag_id, :text)
  end
end

app/controllers/crags_controller.rb
class CragsController < ApplicationController

  def index
    if params[:location_id]
      @crags = Location.find(params[:location_id])
    else
      @crags = Crag.all
    end
  end

  def show
    @crag = Crag.find(params[:id])
    @comment = Comment.new
    @comments = @crag.comments
  end

  def new
    @crag = Crag.new
    @location = Location.find(params[:location_id])
  end

  def create
    @location = Location.find(params[:location_id])
    @crag = @location.crags.build(crag_params)
    if @crag.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def edit
    @crag = Crag.find(params[:id])
    @location = Location.find(params[:location_id])
  end

  def update
    @location = Location.find(params[:location_id])
    @crag = Crag.find(params[:id])
    @crag.update(crag_params)
    redirect_to location_path(@location)
  end

  private

  def crag_params
    params.require(:crag).permit(:name, :region, :rock_type, :season, :location_id, :user_id, :comments => [:text])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
    @location.crags.build
    if @save
      redirect_to locations_path
    else
      render :new
    end
  end

  def create
    @location = Location.new(location_params)
    @location.save
    redirect_to locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, crags_attributes: [:name, :region, :rock_type, :season])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :require_login, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render 'sessions/new'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_login, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.username = params[:user][:username]
    @user.password = params[:user][:password]
    if @user.save
      session[:user_id] = @user.id
      redirect_to locations_path
    else
      render :new
    end
  end

  private

# def user_params
#   params.require(:user).permit(:username, :password_digest)
# end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/crags/edit.html.erb
<h1>Editing <%= @crag.name %></h1>

<%= form_for([@location, @crag]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :region %>
  <%= f.text_field :region %><br>
  <%= f.label :rock_type %>
  <%= f.text_field :rock_type %><br>
  <%= f.label :season %>
  <%= f.text_field :season %>


<br>

  <%= f.submit %>
<% end %>

app/views/crags/new.html.erb
<h1><%= @location.name %></h1>

<%= form_for([@location, @crag]) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :region %>
<%= f.text_field :region %><br>
<%= f.label :rock_type %>
<%= f.text_field :rock_type %><br>
<%= f.label :season %>
<%= f.text_field :season %>


<%= f.submit %>
<% end %>

app/views/crags/show.html.erb
<h1><%= @crag.name %></h1>
Add a Comment:

<%= form_for(@comment) do |f| %>
<%= f.hidden_field :crag_id, :value => @crag.id %>
  <%= f.text_field :text %>
<% end %>
<ul>

<% @comments.each do |comment| %>
<li><%= comment.user.username %> says: <%= comment.text %></li>
<% end %>
</ul>

app/views/home/homepage.html.erb
<h1>Welcome to Cliff Notes!</h1>
<h2><%= link_to "Register", signup_path %> or
<%= link_to "Login", login_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CliffNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<% if logged_in? %>
<h1>Welcome to Cliff Notes, <%= current_user.username.capitalize %>!</h1>
<br>
<% else %>
<h1>Welcome to Cliff Notes</h1>

<% end %>
<ul>
<% @locations.each do |location| %>
<li>
  <h3><%= link_to location.name, location_path(location) %></h3>
</li>
<%  end %>
</ul>
<%= link_to "Add a Location", new_location_path %>

app/views/locations/new.html.erb
<h1>Add a Location</h1>
<%= form_for(@location) do |f| %>
<%= f.label :name %>
<%= f.text_field :name, :placeholder => "enter location name" %><br>
<h2>Now Add a Crag</h2>
<%= f.fields_for :crags do |crag| %>
<p>
<%= crag.label :name %>
<%= crag.text_field :name, placeholder: "crag/area name"%><br>
<%= crag.label :region %>
<%= crag.text_field :region, placeholder: "general area" %><br>
<%= crag.label :rock_type %>
<%= crag.text_field :rock_type, placeholder: "e.g. limestone" %><br>
<%= crag.label :season %>
<%= crag.text_field :season, placeholder: "ideal season" %>
</p>

<% end %>

    <%= f.submit %>
    <% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<%= link_to "New Crag", new_location_crag_path(@location) %>

<h2>Crags:</h2>

<ul>

<% @location.crags.each do |crag| %>

  <h3>Name: <a href="/locations/<%= @location.id %>/crags/<%= crag.id %>"><%= crag.name %></a></h3>
  <p>Region: <%= crag.region %></p>
  <p>Rock Type: <%= crag.rock_type %></p>
  <p>Best Season: <%= crag.season %></p>
  <ul>

  <%= link_to "Edit This Crag", edit_location_crag_path(@location, crag.id) %>
  <br><br>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up as a New User</h1>
<header class="header">

  <%= form_for(@user) do |f| %>
  <%= f.text_field :username, class: "new-todo", placeholder: "name goes here" %>
  <%= f.text_field :password, class: "new-todo", placeholder: "password goes here" %>
  <%= f.submit %>
  <% end %>

  </header>